name: PlatformIO

on: [push, pull_request]

jobs:
  build-main:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Init submodule
      run: git submodule update --init
    - name: Set up Python 3
      uses: actions/setup-python@v1
      with:
        python-version: 3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install platformio 
    - name: Build main
      run: pio run -e main
      
